name: First-Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: first step
              run: ls
